# Generated by Django 4.2.27 on 2026-01-15 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cltId', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Client')),
                ('cltNom', models.CharField(max_length=200, verbose_name='Nom et Prenom')),
                ('cltSegment', models.CharField(choices=[('Consumer', 'CONSUMER'), ('Corporate', 'CORPORATE'), ('Home Office', 'HOME OFFICE')], max_length=20, verbose_name='Segment')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('comID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Commande')),
                ('comDate', models.DateField(verbose_name='Date Commande')),
                ('comDateLivraison', models.DateField(verbose_name='Date Livraison')),
                ('comModeLivraison', models.CharField(max_length=30, verbose_name='Mode Livraison')),
            ],
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('locId', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Localite')),
                ('locCodePostal', models.PositiveIntegerField(unique=True, verbose_name='Code Postal')),
                ('locVille', models.CharField(max_length=50, verbose_name='Ville')),
                ('locEtat', models.CharField(max_length=50, verbose_name='Etat')),
                ('locRegion', models.CharField(choices=[('Central', 'CENTRAL'), ('West', 'WEST'), ('East', 'EAST'), ('South', 'SOUTH')], max_length=10, verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Localisation du Client',
                'ordering': ['locRegion', 'locEtat'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('prodId', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID Produit')),
                ('prodNom', models.CharField(max_length=255, verbose_name='Produit')),
                ('prodCategorie', models.CharField(choices=[('Furniture', 'FURNITURE'), ('Office Supplies', 'OFFICE SUPPLIES'), ('Technology', 'TECHNOLOGY')], max_length=20, verbose_name='Categorie')),
                ('prodSousCategorie', models.CharField(max_length=50, verbose_name='Sous-Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligQuantite', models.IntegerField(verbose_name='Quantité')),
                ('ligPrix', models.FloatField(verbose_name='Prix')),
                ('ligRemise', models.FloatField(default=0, verbose_name='Remise')),
                ('ligBenefice', models.FloatField(default=0, verbose_name='Benefice')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligne_client', to='dashboard.client')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_produits', to='dashboard.commande')),
                ('localite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligne_localite', to='dashboard.localite')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_produits', to='dashboard.produit')),
            ],
            options={
                'verbose_name': 'Ligne de Commande',
                'ordering': ['produit'],
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='comproduits',
            field=models.ManyToManyField(blank=True, related_name='contenir', through='dashboard.Ligne', to='dashboard.produit', verbose_name='Produits'),
        ),
    ]
